const selector = document.getElementById("mensaje");
selector.innerHTML = "CONEXION EXITOSA ENTRE HTML Y JS";
prompt("Preguntar algo");
console.log("Imprimir algo");
const entrada = prompt("¿Que producto desea comprar?");
console.log(entrada);
alert(entrada);
const nombre = prompt("Dime tu name:");
console.log(nombre);
const mensaje = "Bienvenido " + nombre;
alert(mensaje);